// eslint-disable-next-line vue/prefer-import-from-vue
export { isArray, isFunction, isString } from '@vue/shared'

export * from './dedupeHead'
export * from './ensureLeadingSlash'
export * from './ensureEndingSlash'
export * from './formatDateString'
export * from './isLinkExternal'
export * from './isLinkFtp'
export * from './isLinkHttp'
export * from './isLinkMailto'
export * from './isLinkTel'
export * from './isPlainObject'
export * from './removeEndingSlash'
export * from './removeLeadingSlash'
export * from './resolveHeadIdentifier'
export * from './resolveLocalePath'
export * from './resolveRoutePathFromUrl'
