packages:
  - e2e
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

catalogs:
  vite:
    '@vitejs/plugin-vue': ^6.0.8
    '@vitest/coverage-istanbul': ^4.1.10
    rolldown: ^1.2.0
    tsdown: ^0.22.13
    vite: ^8.1.5
    vitest: ^4.1.10
  vue:
    vue: ^3.5.40
    vue-router: ^5.2.0
