export {
  type BuildCommand,
  type BuildCommandOptions,
  type DevCommand,
  type DevCommandOptions,
  type UserConfig,
  cli,
  createBuild,
  createDev,
  defineUserConfig,
  handlePageAdd,
  handlePageChange,
  handlePageUnlink,
  info,
  loadUserConfig,
  resolveAppConfig,
  resolveCliAppConfig,
  resolveUserConfigConventionalPath,
  resolveUserConfigPath,
  transformUserConfigToPlugin,
  watchPageFiles,
  watchUserConfigFile,
} from '@vuepress/cli'
