export {
  type ClientConfig,
  ClientOnly,
  Content,
  type CreateVueAppFunction,
  type Layouts,
  type LayoutsRef,
  type PageData,
  type PageDataRef,
  type PageFrontmatter,
  type PageFrontmatterRef,
  type PageHead,
  type PageHeader,
  type PageHeadRef,
  type PageHeadTitle,
  type PageHeadTitleRef,
  type PageLang,
  type PageLangRef,
  type PageLayoutRef,
  type PageRouteItem,
  type PagesData,
  type PagesDataRef,
  type RouteLocale,
  type RouteLocaleRef,
  type SiteData,
  type SiteDataRef,
  type SiteLocaleData,
  type SiteLocaleDataRef,
  type UpdateHead,
  defineClientConfig,
  layoutsSymbol,
  pageDataEmpty,
  pageDataSymbol,
  pageFrontmatterSymbol,
  pageHeadSymbol,
  pageHeadTitleSymbol,
  pageLangSymbol,
  pageLayoutSymbol,
  pagesData,
  resolvers,
  routeLocaleSymbol,
  siteData,
  siteLocaleDataSymbol,
  updateHeadSymbol,
  useLayouts,
  usePageData,
  usePageFrontmatter,
  usePageHead,
  usePageHeadTitle,
  usePageLang,
  usePageLayout,
  usePagesData,
  useRouteLocale,
  useSiteData,
  useSiteLocaleData,
  useUpdateHead,
  withBase,
} from '@vuepress/client'
