export {
  type AliasDefineHook,
  type App,
  type AppConfig,
  type AppConfigBuild,
  type AppConfigCommon,
  type AppConfigDev,
  type AppDir,
  type AppDirFunction,
  type AppEnv,
  type AppOptions,
  type AppWriteTemp,
  type BuildApp,
  type Bundler,
  type ClientConfigFileHook,
  type DevApp,
  type ExtendsHook,
  type HeadAttrsConfig,
  type HeadConfig,
  type HeadTag,
  type HeadTagEmpty,
  type HeadTagNonEmpty,
  type Hook,
  type HookItem,
  type HookQueue,
  type Hooks,
  type HooksExposed,
  type HooksName,
  type HooksNormalized,
  type HooksResult,
  type LifeCycleHook,
  type LocaleConfig,
  type LocaleData,
  type Page,
  type PageData,
  type PageFrontmatter,
  type PageHeader,
  type PageOptions,
  type Plugin,
  type PluginApi,
  type PluginConfig,
  type PluginFunction,
  type PluginObject,
  type SiteData,
  type SiteLocaleConfig,
  type Theme,
  type ThemeFunction,
  type ThemeInfo,
  type ThemeObject,
  appInit,
  appPrepare,
  appUse,
  createAppDirFunction,
  createBaseApp,
  createBuildApp,
  createDevApp,
  createHookQueue,
  createPage,
  createPluginApi,
  createPluginApiHooks,
  createPluginApiRegisterHooks,
  inferPagePath,
  normalizeAliasDefineHook,
  normalizeClientConfigFileHook,
  prepareClientConfigs,
  preparePageComponent,
  preparePageData,
  preparePagesComponents,
  preparePagesData,
  preparePagesRoutes,
  prepareSiteData,
  renderPageContent,
  resolveAppDir,
  resolveAppEnv,
  resolveAppOptions,
  resolveAppPages,
  resolveAppSiteData,
  resolveAppVersion,
  resolveAppWriteTemp,
  resolvePageComponentInfo,
  resolvePageDataInfo,
  resolvePageDate,
  resolvePageFileContent,
  resolvePageFilePath,
  resolvePageHtmlInfo,
  resolvePageKey,
  resolvePageLang,
  resolvePagePath,
  resolvePagePermalink,
  resolvePageRouteMeta,
  resolvePageSlug,
  resolvePluginObject,
  resolveThemeInfo,
} from '@vuepress/core'
