export type {
  HeadAttrsConfig,
  HeadConfig,
  HeadTag,
  HeadTagEmpty,
  HeadTagNonEmpty,
  LocaleConfig,
  LocaleData,
  PageBase,
  PageData,
  PageFrontmatter,
  PageHeader,
  SiteData,
  SiteLocaleConfig,
  SiteLocaleData,
  VuepressSSRContext,
} from '@vuepress/shared'

export {
  dedupeHead,
  ensureEndingSlash,
  ensureLeadingSlash,
  formatDateString,
  isFunction,
  isLinkExternal,
  isLinkHttp,
  isLinkWithProtocol,
  isPlainObject,
  isString,
  omit,
  removeEndingSlash,
  removeLeadingSlash,
  resolveHeadIdentifier,
  resolveLocalePath,
  resolveRoutePathFromUrl,
} from '@vuepress/shared'
