export {
  type HeadAttrsConfig,
  type HeadConfig,
  type HeadTag,
  type HeadTagEmpty,
  type HeadTagNonEmpty,
  type LocaleConfig,
  type LocaleData,
  type PageBase,
  type PageData,
  type PageFrontmatter,
  type PageHeader,
  type SiteData,
  type SiteLocaleConfig,
  type SiteLocaleData,
  type VuepressSSRContext,
  dedupeHead,
  ensureEndingSlash,
  ensureLeadingSlash,
  formatDateString,
  isFunction,
  isLinkExternal,
  isLinkHttp,
  isLinkWithProtocol,
  isPlainObject,
  isString,
  omit,
  removeEndingSlash,
  removeLeadingSlash,
  resolveHeadIdentifier,
  resolveLocalePath,
  resolveRoutePathFromUrl,
} from '@vuepress/shared'
