// eslint-disable-next-line vue/prefer-import-from-vue
export { isArray, isFunction, isString } from '@vue/shared'

export * from './dedupeHead.js'
export * from './ensureLeadingSlash.js'
export * from './ensureEndingSlash.js'
export * from './formatDateString.js'
export * from './isLinkExternal.js'
export * from './isLinkFtp.js'
export * from './isLinkHttp.js'
export * from './isLinkMailto.js'
export * from './isLinkTel.js'
export * from './isPlainObject.js'
export * from './omit.js'
export * from './removeEndingSlash.js'
export * from './removeLeadingSlash.js'
export * from './resolveHeadIdentifier.js'
export * from './resolveLocalePath.js'
export * from './resolveRoutePathFromUrl.js'
