import { debug } from '@vuepress/utils'
import type { App } from '../types/index.js'
import {
  prepareClientConfigs,
  preparePageComponent,
  preparePageData,
  preparePagesMap,
  prepareSiteData,
} from './prepare/index.js'

const log = debug('vuepress:core/app')

/**
 * Prepare files for development or build
 *
 * - page components
 * - routes
 * - site data
 * - other files that generated by plugins
 */
export const appPrepare = async (app: App): Promise<void> => {
  log('prepare start')

  // generate page component files
  for (const page of app.pages) {
    await preparePageComponent(app, page)
  }

  // generate page data files
  for (const page of app.pages) {
    await preparePageData(app, page)
  }

  // generate pages map
  await preparePagesMap(app)

  // generate site data file
  await prepareSiteData(app)

  // generate client configs file
  await prepareClientConfigs(app)

  // plugin hook: onPrepared
  await app.pluginApi.hooks.onPrepared.process(app)

  log('prepare finish')
}
