import { debug } from '@vuepress/utils'
import type { App } from '../types/index.js'
import {
  prepareClientConfigs,
  preparePageChunk,
  prepareRoutes,
  prepareSiteData,
} from './prepare/index.js'

const log = debug('vuepress:core/app')

/**
 * Prepare files for development or build
 *
 * - page chunks
 * - routes
 * - site data
 * - other files that generated by plugins
 */
export const appPrepare = async (app: App): Promise<void> => {
  log('prepare start')

  await Promise.all([
    ...app.pages.map(async (page) => preparePageChunk(app, page)),
    prepareRoutes(app),
    prepareSiteData(app),
    prepareClientConfigs(app),
  ])

  // plugin hook: onPrepared
  await app.pluginApi.hooks.onPrepared.process(app)

  log('prepare finish')
}
